# Generated by Django 3.1.4 on 2020-12-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=70, null=True)),
                ('details', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Shirts', 'Shirts'), ('Shoes', 'Shoes'), ('Trousers', 'Trousers'), ('Dress', 'Dress')], max_length=200, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Deleviered', 'Deleviered'), ('in progress', 'in progress'), ('out of order', 'out of order')], max_length=200)),
                ('price', models.FloatField(null=True)),
                ('image', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
